# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "pivotal-tracker"
  s.version = "0.5.14"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Justin Smestad", "Josh Nichols", "Terence Lee", "Nick Wargnier"]
  s.date = "2014-07-14"
  s.email = "nick@amitree.com"
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    ".rspec",
    ".travis.yml",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/pivotal-tracker.rb",
    "lib/pivotal-tracker/activity.rb",
    "lib/pivotal-tracker/attachment.rb",
    "lib/pivotal-tracker/client.rb",
    "lib/pivotal-tracker/extensions.rb",
    "lib/pivotal-tracker/iteration.rb",
    "lib/pivotal-tracker/membership.rb",
    "lib/pivotal-tracker/note.rb",
    "lib/pivotal-tracker/project.rb",
    "lib/pivotal-tracker/proxy.rb",
    "lib/pivotal-tracker/story.rb",
    "lib/pivotal-tracker/task.rb",
    "lib/pivotal-tracker/validation.rb",
    "lib/pivotal_tracker.rb",
    "pivotal-tracker.gemspec",
    "spec/fixtures/activity.xml",
    "spec/fixtures/bugs.xml",
    "spec/fixtures/created_note.xml",
    "spec/fixtures/created_story.xml",
    "spec/fixtures/features.xml",
    "spec/fixtures/iterations_all.xml",
    "spec/fixtures/iterations_backlog.xml",
    "spec/fixtures/iterations_current.xml",
    "spec/fixtures/iterations_current_backlog.xml",
    "spec/fixtures/iterations_done.xml",
    "spec/fixtures/memberships.xml",
    "spec/fixtures/notes.xml",
    "spec/fixtures/project.xml",
    "spec/fixtures/project_activity.xml",
    "spec/fixtures/projects.xml",
    "spec/fixtures/stale_fish.yml",
    "spec/fixtures/stories.xml",
    "spec/fixtures/story-4459994.xml",
    "spec/fixtures/story-4460038.xml",
    "spec/fixtures/story-4460598.xml",
    "spec/fixtures/story-4473735.xml",
    "spec/fixtures/tasks.xml",
    "spec/fixtures/update_tasks.xml",
    "spec/pivotal-tracker/activity_spec.rb",
    "spec/pivotal-tracker/attachment_spec.rb",
    "spec/pivotal-tracker/client_spec.rb",
    "spec/pivotal-tracker/iteration_spec.rb",
    "spec/pivotal-tracker/membership_spec.rb",
    "spec/pivotal-tracker/note_spec.rb",
    "spec/pivotal-tracker/project_spec.rb",
    "spec/pivotal-tracker/story_spec.rb",
    "spec/pivotal-tracker/task_spec.rb",
    "spec/spec_helper.rb",
    "spec/support/stale_fish_fixtures.rb"
  ]
  s.homepage = "http://github.com/jsmestad/pivotal-tracker"
  s.require_paths = ["lib"]
  s.rubygems_version = "2.0.7"
  s.summary = "Ruby wrapper for the Pivotal Tracker API"
  s.licenses    = ['MIT']
  s.description = 'Forked pivotal-tracker gem'


  s.add_runtime_dependency 'rest-client', '~> 1.6', '>= 1.6.0'
  s.add_runtime_dependency 'nokogiri-happymapper', '~> 0.5', '>= 0.5.4'
  s.add_runtime_dependency 'builder', '~> 0'
  s.add_runtime_dependency 'crack', '~> 0'
  s.add_runtime_dependency 'happymapper', '~> 0.3', '>= 0.3.2'
  s.add_runtime_dependency 'nokogiri', '~> 1.4', '>= 1.4.3'
  s.add_development_dependency 'rspec', '~> 2.14'
  s.add_development_dependency 'bundler', '~> 1.0', '>= 1.0.12'
  s.add_development_dependency 'jeweler', '~> 0'
  s.add_development_dependency 'stale_fish', '~> 1.3', '>= 1.3.0'
end

